### ISSUE TITLE
Feature request: Support multiple AWS Profiles

### ISSUE THREAD

**Issue by bigman73** [mhassan1/yarn-plugin-aws-codeartifact#1]
Currently the aws-codeartifact plugin (v0.4) works well but always uses the default AWS profile on the machine.
When a user has multiple configured AWS name profiles then it is possible to use a specific profile by adding the `export AWS_PROFILE={profile-name}` in front of every yarn command
But, this solution is tedious, error prone and potentially dangerous. Omitting the aws profile by mistake may lead to falling back unintentionally to the default AWS profile.

1. The plugin could first try to use an env variable `PLUGIN_AWS_CA_PROFILE`. If such an env variable exists then use it instead of the default
This will allow a developer to globally use all yarn operations through a specific AWS profile
2. Then the plugin could try to read a user defined configuration file, `plugin-aws-codeartifact.yml` within the project. That file is not part of the plugin, and may be untracked.
If the file exists and there is an AWS_PROFILE entry in it then its value would be used, not the default
3. Otherwise, fall back and use the default AWS profile

**Comment by mhassan1** [comment]
One challenge I see with the environment variable approach is that the plugin currently allows fine-grained control over which registry to use in different scenarios: e.g. publishing vs. reading, different scopes with `npmScopes`. A single variable does not align with that.

I like the idea of the YAML configuration file, which could be placed in the project directory or any parent directory, including the home directory. The structure of the YAML file could be similar to the core `.yarnrc.yml` file, e.g.:
```
# .yarn-plugin-aws-codeartifact.yml
npmRegistryServerConfig:
  awsProfile: my-profile-1
npmPublishRegistryConfig:
  awsProfile: my-profile-2
npmScopes:
  my-scope:
    npmRegistryServerConfig:
      awsProfile: my-profile-3
npmRegistries:
  //my-registry.com
    awsProfile: my-profile-4
```
Then, as we are resolving the registries during the command execution, we can use the configured profile for each registry configuration (or fall back to the default for each).
